### ISSUE TITLE
请问一下在reactnative 中怎么使用

### ISSUE THREAD

**Issue by liwei1991** [xuexiangjys/XUpdate#1]
我是在reactNative中使用的，在MainActivity使用
XUpdate.newBuild(MainActivity.this)
                .updateUrl(mUpdateUrl)
                .update();
报错: 使用默认的版本更新提示器，context必须传FragmentActivity！
不会安卓只是想在集成在我的reactNative 应用中使用，谢谢

**Comment by liwei1991** [comment]
没有Fragment如果在MainActivity中使用默认更新提示器呢context怎么传

**Comment by xuexiangjys** [comment]
因为默认提供的更新提示器是使用DialogFragment实现的，context必须传FragmentActivity.但是ReactNative默认的activity是ReactActivity，他的父类是Activity而非FragmentActivity，所有如果需要使用的话，需要更换默认更新提示器的实现，你可以参见文档说明。我会在后续的版本里增加React-Native的支持。如果比较急的话，你可以直接在QQ群里联系我，谢谢🙏
