### ISSUE TITLE
优化：建议

### ISSUE THREAD

**Issue by SmallWinter** [xuexiangjys/XUpdate#100]
首先感谢作者，不辞辛劳提供开源库。
个人拙见，作者可以看看：
1. 库稍微有点儿重，可以考虑逐渐去除三方的依赖。
2.大多数人都是懒的，如果能增加默认的请求下载service，包括一些默认配置，尽可能一句话初始化，效果可能会有大的提升。

再次感谢作者，只是个人建议，仅供参考。

**Comment by xuexiangjys** [comment]
首先还是感谢你的建议,只是我不太认同.

我不太明白你的意思: 库稍微有点儿重，可以考虑逐渐去除三方的依赖.
我这库貌似除了引用androidx.appcompat和gson库以外,没有别的第三方库了吧.而且这两个基本开发都需要,重吗?
如果这都觉得重,是不是直接用个工具类岂不是更香?
而且你这两个建议前后矛盾.一个是去库嫌重,一个又让我多加点默认实现,你的思维有点混乱了吧.

另外,这个项目本身的定位就不是方便快捷,不是为懒人提供的,如果你觉得用起来不方便,你可以尝试在我的框架的基础上加一下这些默认实现,然后我可以把链接加到文档中.

**Comment by fiterzs** [comment]
感谢作者的辛勤劳动与付出，
我看到在例子中的依赖库如下
 implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.1'
    implementation 'com.github.xuexiangjys:XUpdate:2.0.2'
    implementation 'com.github.xuexiangjys.XUtil:xutil-core:1.1.8'
    implementation 'com.github.xuexiangjys.XPage:xpage-lib:3.0.0'
    implementation 'com.squareup.okhttp3:okhttp:3.10.0'
    annotationProcessor 'com.github.xuexiangjys.XPage:xpage-compiler:3.0.0'
    implementation 'com.github.xuexiangjys.XUtil:xutil-sub:1.1.8'
    implementation 'io.reactivex.rxjava2:rxjava:2.2.0'
    implementation 'io.reactivex.rxjava2:rxandroid:2.1.0'
    implementation 'com.zhy:okhttputils:2.6.2'
    implementation 'com.github.xuexiangjys:XHttp2:2.0.0'
    implementation 'com.github.xuexiangjys.XAOP:xaop-runtime:x1.0.5'  //添加依赖
    implementation group: 'com.google.code.gson', name: 'gson', version: '2.8.5'

好像很多都是相互依赖的

**Comment by xuexiangjys** [comment]
一键使用,并且支持断点续传可以参考如下项目:

https://github.com/xuexiangjys/XUpdateAPI
