### ISSUE TITLE
Md5Utils.getFileMD5(file) 报错

### ISSUE THREAD

**Issue by dancheng99** [xuexiangjys/XUpdate#101]
**问题描述（必填）**
 String s = Md5Utils.getFileMD5(file); 报错 java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)

**使用的XUpdate版本（必填）**
implementation 'com.github.xuexiangjys:XUpdate:2.0.1'

**如何重现（必填）**
import com.xuexiang.xupdate.utils.Md5Utils;
...

File extDir = Environment.getExternalStoragePublicDirectory(DIRECTORY_DOWNLOADS);
                String filename = "2.apk";
                File file = new File(extDir, filename);

                System.out.println(file.isFile());  //这里是true 
                System.out.println(file); 
                
                 //这里报错  
                //java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
                String s = Md5Utils.getFileMD5(file); 
               

**设备信息**
小米8真机
 
要被md5搞疯了

**Comment by xuexiangjys** [comment]
水平不够就直接安装我的apk获取一下值不就完事了,一丁点Android的知识都没有,我怎么教你????

**Comment by dancheng99** [comment]
> 水平不够就直接安装我的apk获取一下值不就完事了,一丁点Android的知识都没有,我怎么教你????
> 下载目录是需要权限的,不是你有就能获取的,知道不?

我刚开始学Android，我也加了权限的 文件已经读到了 调用报错

**Comment by xuexiangjys** [comment]
> > 水平不够就直接安装我的apk获取一下值不就完事了,一丁点Android的知识都没有,我怎么教你????
> > 下载目录是需要权限的,不是你有就能获取的,知道不?
> 
> 我刚开始学Android，我也加了权限的 文件已经读到了 调用报错

给初学者一点建议，那就是切勿好高骛远，还没学会走，就想开始跑是不行的。
你认为你加权限了就好了？报错就是` java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)`文件找不到，你服不服？你认为的就是对的吗？
咱初学者能不能把身份放第一点，看看别人是怎么写的，先学会模仿行不行？
https://github.com/xuexiangjys/XUpdate/blob/master/app/src/main/java/com/xuexiang/xupdatedemo/fragment/FileMD5Fragment.java
不要再问来问去了，别人的时间也是时间，别人没有义务天天教你
