### ISSUE TITLE
请问一下安装问题

### ISSUE THREAD

**Issue by bang88** [xuexiangjys/XUpdate#102]
**提 Bug 前需要做的事情**

1.如果是集成问题的话，请保证仔细按照[如何引用](https://github.com/xuexiangjys/XUpdate/wiki/%E5%A6%82%E4%BD%95%E5%BC%95%E7%94%A8)的步骤，一步一步来，不要跳步骤！ 2.详细阅读过[使用手册](https://github.com/xuexiangjys/XUpdate/wiki)，并且确保是框架的问题。 3.参考[常见问题](https://github.com/xuexiangjys/XUpdate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98),可以解决你出现的绝大多数问题!

> 如果以上都不能解决你的问题,那么请按照以下说明仔细填写信息,这里需要说明的是:不符合填写要求的 issue 一律不予理会,希望这样能节约大家的时间!

---

**问题描述（必填）**
对问题进行清晰而简明的描述，把握问题的关键点。

**使用的 XUpdate 版本（必填）**

**如何重现（必填）**
重现的步骤:

1. 已经提示更新，并且下载成功了。 点击安装的时候系统提示允许了未知来源的安装，但是安装到最后说 未能安装应用。

请问这个是什么问题？

**期望的效果**
对你期望的效果进行清晰而简明的描述。

**截图**
如果方便的话，贴一下程序截图和代码片段以帮助解释您的问题。

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题

- 设备名: Google Pixel 3XL
- Android 版本: 10
- 设备型号 [e.g. ]
- 系统版本（手机厂商定制 rom）

**附加信息**
React-Native 版本，初始化什么的都没有问题，也可以正常下载下来了。

我加了 error 没有什么信息返回

```tsx
const res = await XUpdate.updateByInfo(new UpdateArgs(), {
  hasUpdate: true,
  versionCode: 1,
  versionName: AppInfo.Version,
  updateContent: AppInfo.ChangeLog,
  downloadUrl: AppInfo.Url,
  isForce: true,
  //选填
  isIgnorable: false
  // apkSize: AppInfo.Size,
});
console.log(res);
XUpdate.addErrorListener = (listener: Function) => {
  console.log(listener);
};
```

**Comment by xuexiangjys** [comment]
就不能先看一下文档吗？
https://github.com/xuexiangjys/XUpdate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#6%E9%97%AE%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E6%9C%80%E6%96%B0%E7%9A%84%E5%BA%94%E7%94%A8%E4%B8%8B%E8%BD%BD%E4%BA%86%E4%BD%86%E6%98%AF%E7%82%B9%E5%87%BB%E5%AE%89%E8%A3%85%E6%8C%89%E9%92%AE%E5%90%8E%E4%B8%80%E7%9B%B4%E6%8F%90%E7%A4%BA%E6%9B%B4%E6%96%B0%E5%A4%B1%E8%B4%A5%E5%91%A2

**Comment by bang88** [comment]
肯定看了啊。 正常能下载安装的，我没有配置MD5

**Comment by xuexiangjys** [comment]
你这种情况，八成是签名不对或者其他问题导致的。只要是调出了系统的安装界面，基本就和框架无关了

**Comment by xuexiangjys** [comment]
麻烦仔细看行不行，怎么又扯到MD5了？

**Comment by bang88** [comment]
所以想请教一下，知不知道是哪里的问题，因为单独浏览器下载apk文件可以安装。

**Comment by xuexiangjys** [comment]
请按上面的4步慢慢排查行不行？

**Comment by bang88** [comment]
打扰。。。

**Comment by xuexiangjys** [comment]
> 打扰。。。

？？？？
