### ISSUE TITLE
关于授权读写权限的疑问

### ISSUE THREAD

**Issue by ff-frida** [xuexiangjys/XUpdate#105]
----

**问题描述（必填）**
app只配置了读写权限在配置文件，但是不申请读写权限。
这样点击更新也能下载到apk，然后正常安装。这是属于正常预期吗？

也就是，只要配置了读写权限，然后不申请，也能正常升级的吧。
nexus 5，红米8a
 不申请读写权限也能正常下载升级app。
app的target = 27

**使用的XUpdate版本（必填）**
最新版本

**如何重现（必填）**
重现的步骤:
 

**期望的效果**
 

**截图**
如果方便的话，贴一下程序截图和代码片段以帮助解释您的问题。

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
nexus 5，红米8a
 
**附加信息**
在此处添加任何有关该问题的任何其他说明。

**Comment by xuexiangjys** [comment]
框架默认存储的目录是私有目录，是不需要读写权限的。
只有在公有目录才需要申请权限，知道不？还是不懂的话，建议把基础打扎实。
