### ISSUE TITLE
图片显示异常

### ISSUE THREAD

**Issue by xuhang96** [xuexiangjys/XUpdate#111]
**问题描述（必填）**
日志太长导致按钮需要下滚，图片背景显示透明，异常显示，详见图片

**使用的XUpdate版本（必填）**
2.0.2

**如何重现（必填）**
重现的步骤:
1. 日志太长

**期望的效果**
希望图片背景能显示

**截图**
![image](https://user-images.githubusercontent.com/45863623/98317907-658d6000-2018-11eb-87cc-21d438a353d2.png)

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
 - 设备名: [魅族MX5]
 - Android版本: [Android 5.1]
 - 设备型号 [MX5 ]
 - 系统版本（Flyme 6.3.5.0A）

**Comment by xuexiangjys** [comment]
已优化:
eae86f93f1ad31983f4eddd575e4c6ed172ac5c8
