### ISSUE TITLE
静默更新

### ISSUE THREAD

**Issue by SevenTxT** [xuexiangjys/XUpdate#114]
**问题描述（必填）**
您好，请问我在虚拟设备上已经赋予了超级权限（root），为什么在静默更新的时候，它还是需要我点击安装，而不是自动安装完毕？（ 因为要使用root权限，所以采用了虚拟设备）

**使用的XUpdate版本（必填）**
2.0.3

**如何重现（必填）**
重现的步骤:
1. 加入请求root权限的代码
2. 打开app赋予root权限
3. 点击   版本更新（自动模式）

**期望的效果**
自动下载后自动安装，而不是需要手动点击install

**截图**
![example](https://user-images.githubusercontent.com/46442465/99506400-fff88680-29bc-11eb-9f1c-e3202ec207ae.gif)

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
 - 设备名: [虚拟设备]
 - Android版本: [Android 5.1]
 - 设备型号 [ ]
 - 系统版本（）

**Comment by xuexiangjys** [comment]
可以尝试自定义OnInstallListener或者重写DefaultInstallListener,可能方法不兼容,静默安装本身就和手机的rom有关.
