### ISSUE TITLE
1使用updateDialogActivity作为弹窗提示的话，点击升级无法显示进度条，好像是因为FileDownLoadLisenter使用了弱应用引起的。我取消弱引用就OK了

### ISSUE THREAD

**Issue by cc365774016** [xuexiangjys/XUpdate#115]

**Comment by xuexiangjys** [comment]
你可以试一下最新的代码:
93dfa65a31e45d31f89bc1478d53692b205cfd8c

**Comment by cc365774016** [comment]
我用的就是最新的2.0.3版本

**Comment by xuexiangjys** [comment]
你不看的嘛,这是我昨天刚修复过的????

**Comment by cc365774016** [comment]
我是昨天下午用的。我等会引用最新本地库试试

**Comment by xuexiangjys** [comment]
还没发版本,我的意思是你试一下demo还有没有问题

**Comment by cc365774016** [comment]
好的

**Comment by xuexiangjys** [comment]
弱引用是肯定不能取消的,否则就内存泄漏了

**Comment by snowoverflow** [comment]
这个问题好像还存在。
`    @Override
    public void onProgress(float progress, long total) {
        if (getDownloadListener() != null) {
            getDownloadListener().onProgress(progress, total);
        }
    }`
这个地方拿到的downLoadListener一直都是null，无法条用onProgress更新进度。

**Comment by xuexiangjys** [comment]
年轻人要讲武德,怀疑有问题应该拿出证据,而不是靠猜.

**Comment by xuexiangjys** [comment]
> 这个问题好像还存在。
> ` @Override public void onProgress(float progress, long total) { if (getDownloadListener() != null) { getDownloadListener().onProgress(progress, total); } }`
> 这个地方拿到的downLoadListener一直都是null，无法条用onProgress更新进度。

这个问题应该在2.0.6版本上修复好了,你可以试一下
