### ISSUE TITLE
AndroidX下载失败

### ISSUE THREAD

**Issue by lahala** [xuexiangjys/XUpdate#121]
错误提示指向的是com.zhy:okhttputils这个依赖库，然后发现这个库也早已不支持AndroidX，是吧

**Comment by lahala** [comment]
知道如何解决了哈 
 <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="${applicationId}.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/update_file_paths"/>
        </provider>

**Comment by lahala** [comment]
<provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="${applicationId}.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/update_file_paths"/>
        </provider>

**Comment by lahala** [comment]
![Xnip2021-02-02_18-53-32](https://user-images.githubusercontent.com/9395580/106590363-f75d2880-6587-11eb-9bb0-0add6232c3a5.jpg)

由于是老项目升级，然后AndroidX必须添加provider且包含update_file_paths

**Comment by lahala** [comment]
安卓10下载失败，安卓11，竟然可以，报错如下
![Xnip2021-02-03_15-26-45](https://user-images.githubusercontent.com/9395580/106712746-5bd5c180-6634-11eb-9426-a316b863f4b2.jpg)

**Comment by xuexiangjys** [comment]
因为默认下载器没有适配沙盒，请不要设置下载文件路径

**Comment by lahala** [comment]
大佬，一句话，醍醐灌顶哈！！希望此库越来越好，star越来越多！！
