### ISSUE TITLE
android 11下载版本后不能自动安装

### ISSUE THREAD

**Issue by huohuoyoyo** [xuexiangjys/XUpdate#123]
**使用的XUpdate版本 2.0.6

android 11 版本更新下载成功后不能自动安装升级

 - 设备名: [小米 cc9pro]
 - Android版本: [ Android 11]
 - 设备型号 [e.g. ]
 - 系统版本（miui 12.1.3）

**Comment by xuexiangjys** [comment]
请按照模版填写有用的信息,把问题描述清楚,谢谢

**Comment by huohuoyoyo** [comment]
android 11 下载失败

点击更新提示下载失败
![image](https://user-images.githubusercontent.com/12482839/110882621-3b78e100-831d-11eb-9c44-cf94cae92d82.png)
![image](https://user-images.githubusercontent.com/12482839/110882704-4f244780-831d-11eb-9424-ea04a5cb401f.png)

设备名: [小米 ]
Android版本: [ Android 11]
设备型号 [cc9pro ]
系统版本（miui 12.1.3）

**Comment by huohuoyoyo** [comment]
> **使用的XUpdate版本 2.0.6
> 
> android 11 版本更新下载成功后不能自动安装升级
> 
> * 设备名: [小米 cc9pro]
> * Android版本: [ Android 11]
> * 设备型号 [e.g. ]
> *

> 请按照模版填写有用的信息,把问题描述清楚,谢谢
可以close了

**Comment by xuexiangjys** [comment]
....
