### ISSUE TITLE
可以添加自定义通知栏小图标吗

### ISSUE THREAD

**Issue by SmartVive** [xuexiangjys/XUpdate#127]
现在用的是xupdate_icon_app_update.png这个资源，不太符合需求，想换成自己应用的icon

**Comment by xuexiangjys** [comment]
直接覆盖就可以了

**Comment by SmartVive** [comment]
就是想问问可以增加一个公开方法吗，直接覆盖的话要先下载整个工程引入吧

**Comment by xuexiangjys** [comment]
不是啊,你在你的项目文件夹下直接覆盖就可以了
