### ISSUE TITLE
断网的时候进度变成了0

### ISSUE THREAD

**Issue by gaojuanjuan** [xuexiangjys/XUpdate#128]
**提Bug前需要做的事情**

1.如果是集成问题的话，请保证仔细按照[如何引用](https://github.com/xuexiangjys/XUpdate/wiki/%E5%A6%82%E4%BD%95%E5%BC%95%E7%94%A8)的步骤，一步一步来，不要跳步骤！
2.详细阅读过[使用手册](https://github.com/xuexiangjys/XUpdate/wiki)，并且确保是框架的问题。
3.参考[常见问题](https://github.com/xuexiangjys/XUpdate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98),可以解决你出现的绝大多数问题!

> 如果以上都不能解决你的问题,那么请按照以下说明仔细填写信息,这里需要说明的是:不符合填写要求的issue一律不予理会,希望这样能节约大家的时间!

----

**问题描述（必填）**
在下载的过程中，断开网络，进度变成了0

**使用的XUpdate版本（必填）**
2.0.6

**如何重现（必填）**
重现的步骤:
点击“升级”，下载到一半，网络断开，进度变为了0

**期望的效果**
断开网络时进度应该保持不变，不能是0

**Comment by xuexiangjys** [comment]
断网了难道不应该是报错停止中断了吗，哪来的0？
