### ISSUE TITLE
更新提示已是最新版本

### ISSUE THREAD

**Issue by purgeyao** [xuexiangjys/XUpdate#129]
**提Bug前需要做的事情**

1.如果是集成问题的话，请保证仔细按照[如何引用](https://github.com/xuexiangjys/XUpdate/wiki/%E5%A6%82%E4%BD%95%E5%BC%95%E7%94%A8)的步骤，一步一步来，不要跳步骤！
2.详细阅读过[使用手册](https://github.com/xuexiangjys/XUpdate/wiki)，并且确保是框架的问题。
3.参考[常见问题](https://github.com/xuexiangjys/XUpdate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98),可以解决你出现的绝大多数问题!

> 如果以上都不能解决你的问题,那么请按照以下说明仔细填写信息,这里需要说明的是:不符合填写要求的issue一律不予理会,希望这样能节约大家的时间!

----

**问题描述（必填）**
真机debug 是有更新提示的
打包出的app  更新提示已是最新版本
混淆模式已经开启  proguard-rules.pro  文件配置有 `-keep class com.xuexiang.xupdate.entity.** { *; }`

**使用的XUpdate版本（必填）**
1.0.2

**Comment by purgeyao** [comment]
项目为 https://github.com/xuexiangjys/flutter_template  默认配置

**Comment by xuexiangjys** [comment]
flutter项目请去flutter项目下看文档，不要乱提，ok？
