### ISSUE TITLE
下载完后通知栏没更新

### ISSUE THREAD

**Issue by HeavenWen** [xuexiangjys/XUpdate#132]
**使用的XUpdate版本**
最新版本demo

**如何重现**
重现的步骤:
点击的是默认app+自定义api，并设置了后台更新，apk文件换成了比较大的文件80MB左右。当点击后台更新后，home键退出到桌面，查看通知栏情况。下载完成有时候会显示下载完成，点击安装，有时候会显示正在下载，100%。

**截图**
![image](https://user-images.githubusercontent.com/21034493/120315308-cb239f80-c30e-11eb-9a4a-5dcfe17f60d6.png)

**设备信息**
vivo z3 android9

**Comment by xuexiangjys** [comment]
请提供apk的下载链接以及设备的信息

**Comment by HeavenWen** [comment]
> 请提供apk的下载链接以及设备的信息
apk的下载链接
https://dldir1.qq.com/qqfile/qq/edu/eduandroid/tencentedu_6.5.5.22_b76532_2017.apk
设备的信息
vivo z3 android9

**Comment by xuexiangjys** [comment]
已解决:
dcb479e034b374109e8af2a6eb18d3b6167f07e3
