### ISSUE TITLE
无法下载文件

### ISSUE THREAD

**Issue by csyaonie** [xuexiangjys/XUpdate#134]
**问题描述（必填）**
apk还没开始下载（进度条也没动，0%，就开始校验md5），日志确打出下载完毕并开始校验md5，最后的结果就是md5校验失败

**使用的XUpdate版本（必填）2.0.8

**如何重现（必填）**
重现的步骤:
初始化之后
进入mainactivity
调用
 XUpdate.newBuild(this)
                .updateUrl(mUpdateUrl)
                .update()

进度条还是%瞬间就日志就提示下载完毕，就一秒时间不可能下载完成了
D/[XUpdate]: 正在回收资源...
D/[XUpdate]: 更新文件下载完成, 文件路径:/storage/emulated/0/Android/data/com.csyaonie.meituhai/cache/xupdate/1.0.4/meituhai.apk
W/System.err: 安装APK失败！(Apk file verify failed, please check whether the MD5 value you set is correct！)

**期望的效果**
正确下载apk文件

**截图**
如果方便的话，贴一下程序截图和代码片段以帮助解释您的问题。

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
 - 设备名: [小米6x]
 - Android版本: [e.g. Android 7.0]

**Comment by xuexiangjys** [comment]
你不应该问你自己为什么下载不下来嘛?为什么别人能下载而你却不行呢?
日志不是告诉你了嘛,你下的文件有问题.
出现问题难道不应该自己先思考一下的嘛,文档看了吗?
https://github.com/xuexiangjys/XUpdate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#6%E9%97%AE%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E6%9C%80%E6%96%B0%E7%9A%84%E5%BA%94%E7%94%A8%E4%B8%8B%E8%BD%BD%E4%BA%86%E4%BD%86%E6%98%AF%E7%82%B9%E5%87%BB%E5%AE%89%E8%A3%85%E6%8C%89%E9%92%AE%E5%90%8E%E4%B8%80%E7%9B%B4%E6%8F%90%E7%A4%BA%E6%9B%B4%E6%96%B0%E5%A4%B1%E8%B4%A5%E5%91%A2

**Comment by csyaonie** [comment]
@xuexiangjys thank you for you answers. 

这里有个小技巧，可以将后端返回的json直接设置为demo的json 下载xupdate 的更新包
{
  "Code": 0,
  "Msg": "",
  "UpdateStatus": 1,
  "VersionCode": 3,
  "VersionName": "1.0.2",
  "UploadTime": "2018-07-10 17:28:41",
  "ModifyContent": "\r\n1、优化api接口。\r\n2、添加使用demo演示。\r\n3、新增自定义更新服务API接口。\r\n4、优化更新提示界面。",
  "DownloadUrl": "https://xuexiangjys.oss-cn-shanghai.aliyuncs.com/apk/xupdate_demo_1.0.2.apk",
  "ApkSize": 2048,
  "ApkMd5": "E4B79A36EFB9F17DF7E3BB161F9BCFD8"
}
可以成功下载，安装的时候 会提示与原app签名不一致，那么基本就可以确定接入正确。
接下来就要排查自己的这边后端的问题，apk包下载路径是否有权限拦截，手动下载apk包是否能安装等问题。
我的问题其实是因为apk下载地址有权限拦截，但是我是网页是登录状态所以可以下载，但其实app访问是被拦截到了登录页面
