### ISSUE TITLE
google play not support this

### ISSUE THREAD

**Issue by zhubinsheng** [xuexiangjys/XUpdate#136]
将含有此sdk的app上传到谷歌商店后会被审查，审查后app会被下架

**Comment by zhubinsheng** [comment]
![7d6edafeccae9ce6c09f947ef27c8b9](https://user-images.githubusercontent.com/44765143/131602492-ffa3e97e-2f3e-4daf-8246-5c08b4c06989.jpg)
我需要使用此库，因为直接安装的用户用此种功能更新；谷歌用户使用谷歌商店更新，

**Comment by sunwen0402** [comment]
谷歌商店上架的App 不允许使用 除谷歌商店之外的安装方式, 包括App内部更新或者引导其他下载界面, 我们海外的项目之前也被下架过, 后面升级就直接跳转到谷歌商店,或者通过webview 打开网页版的谷歌商店才通过

**Comment by zhubinsheng** [comment]
> 谷歌商店上架的App 不允许使用 除谷歌商店之外的安装方式, 包括App内部更新或者引导其他下载界面, 我们海外的项目之前也被下架过, 后面升级就直接跳转到谷歌商店,或者通过webview 打开网页版的谷歌商店才通过

感谢回复，那么你们在aab中删除了XUpdate是吗？请问有相关脚本可以在打包的时候自动删除吗，这样在打包普通的apk时可以依然保留XUpdate模块。 另外请问如果使用XUpdate的module而不是implement引用，这样是否还会被谷歌查到？

**Comment by sunwen0402** [comment]
当时我们着急上架, 为了安全起见, 相关代码全部移除了, 不知道包含模块不引用会不会被查出来

**Comment by zhubinsheng** [comment]
我觉得不会 因该谷歌无法拿到具体代码的逻辑。这样就可以在代码中判断，而不用做两件同样的事情了

**Comment by xuexiangjys** [comment]
可以在下载的地方做一下兼容, 如果设置的下载地址mDownloadUrl是html网页的话,可以直接跳转网页.
78cd09e370f0946eb5c3502279f39458f8aeaabd
