### ISSUE TITLE
下载失败

### ISSUE THREAD

**Issue by MikeVoy** [xuexiangjys/XUpdate#137]
**问题描述（必填）**
只是用了下载功能
弹出更新框,点击更新 直接报下载失败, 部分机型偶发下载失败不是必现的,
**使用的XUpdate版本（必填）**
2.0.8
**如何重现（必填）**
进入首页更新点击更新 直接报失败
**期望的效果**
规避下载失败的问题,
**截图**
![QQ图片20210915104115](https://user-images.githubusercontent.com/40830151/133361571-3303288e-4eea-4f8b-853b-702f16299ae0.png)

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
 - 设备名:OPPO Reno3
 - Android版本: [Android 11]
 - 设备型号 [e.g. ]
 - 系统版本（colors V11.1）
**附加信息**
这个我有点拿不准哪边的问题 , 报的文件已存在,正常来说下载多次不应该是直接覆盖老文件吗,不知道为什么会有文件已存在的报错, 光使用下载功能我这边只是指定了一个下载目录....所以没有什么好的方法规避

**Comment by xuexiangjys** [comment]
XUpdate.newBuild(getActivity())
                // 注意在Android10及以上存在存储权限问题，不建议设置在外部存储下载目录
                .apkCacheDir(PathUtils.getAppExtCachePath())
                .build()
