### ISSUE TITLE
下载文件类型

### ISSUE THREAD

**Issue by Er-Dong-Chen** [xuexiangjys/XUpdate#138]
目前想下载wgt热更新的包，然后返回文件路径自行安装，但是每次下载的文件最后的类型都是apk的，请问大佬这个可以做到吗

**Comment by xuexiangjys** [comment]
这个可以做到,只需要重写一下IUpdateHttpService的download方法(话说这个IUpdateHttpService本身就是使用者自定义的), 让其支持下载wgt热更新的包

**Comment by xuexiangjys** [comment]
不过最简单的方法还是重写UpdateUtils中的getApkNameByDownloadUrl方法和getApkFileByUpdateEntity方法

**Comment by Er-Dong-Chen** [comment]
搜嘎,大佬真奈斯,全方便自定义呀,可以支持安装wgt热更新的包吗？
