### ISSUE TITLE
  flutter_xupdate: ^2.0.0 升级窗多次调用弹起多次问题

### ISSUE THREAD

**Issue by superpunch** [xuexiangjys/XUpdate#140]
**提Bug前需要做的事情**

1.如果是集成问题的话，请保证仔细按照[如何引用](https://github.com/xuexiangjys/XUpdate/wiki/%E5%A6%82%E4%BD%95%E5%BC%95%E7%94%A8)的步骤，一步一步来，不要跳步骤！
2.详细阅读过[使用手册](https://github.com/xuexiangjys/XUpdate/wiki)，并且确保是框架的问题。
3.参考[常见问题](https://github.com/xuexiangjys/XUpdate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98),可以解决你出现的绝大多数问题!

> 如果以上都不能解决你的问题,那么请按照以下说明仔细填写信息,这里需要说明的是:不符合填写要求的issue一律不予理会,希望这样能节约大家的时间!

----

**问题描述（必填）**
对问题进行清晰而简明的描述，把握问题的关键点。
作者您好。因为我们的app是一直开启的状态 所以当升级窗起后 无人点击的时候 下次再次调用  会弹起新的窗口会覆盖在上面

**使用的XUpdate版本（必填）**
  flutter_xupdate: ^2.0.0

**如何重现（必填）**
重现的步骤:
多次调用
      FlutterXUpdate.updateByInfo(updateEntity: customParseJson(_customJson));
会弹起多个窗口

**期望的效果**
对你期望的效果进行清晰而简明的描述。
如果升级窗在前端显示中。后续再多次调起升级窗 只显示一次 
1.关闭之前窗口 显示最新的窗口
2.提供 ‘关闭窗口‘，’是否有正在显示窗口’ 的接口字段
这两种都可以 

**截图**
如果方便的话，贴一下程序截图和代码片段以帮助解释您的问题。
    _updateTimer = new Timer.periodic(new Duration(seconds: 30), (timer) {
      //弹窗
      checkUpdateByUpdateEntity();
    });
**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
没有root的手机 测试了两个华为手机 都可以重现

**附加信息**
谢谢作者为flutter做出的贡献

**Comment by superpunch** [comment]
全屏状态 发现弹窗后 顶部的状态栏会显示出来。如果能提供 ‘关闭窗口‘，’是否有正在显示窗口’ 的接口字段最好了

**Comment by liruqian** [comment]
遇到同样的问题，建议作者把更新的页面启动方式做出sigleTop模式

**Comment by xuexiangjys** [comment]
已解决
f9a782d1601292f7f545ac172ac6bc2490554fb7
