### ISSUE TITLE
用户忽略升级后，如何重新触发升级？

### ISSUE THREAD

**Issue by kiddkyd1412** [xuexiangjys/XUpdate#143]
情况：
如果当前版本是允许忽略的，用户点击忽略升级后，那么下次打开，将不会再弹框。

需求：
如果用户想主动检测更新的话，有什么办法，可以重新唤起弹框？

**Comment by xuexiangjys** [comment]
目前的设计就是忽略版本之后,本地就永远不会接受这个版本.
否则,你可以重写IUpdateChecker对应的接口,实现你自己的逻辑
