### ISSUE TITLE
ShellUtils execCommand方法报错： Cannot run program "su": error=13, Permission denied

### ISSUE THREAD

**Issue by zhubinsheng** [xuexiangjys/XUpdate#145]
**问题描述（必填）**
ShellUtils execCommand方法报错： Cannot run program "su": error=13, Permission denied

**使用的XUpdate版本（必填）**
最新 com.github.xuexiangjys:XUpdate:2.1.1'

**如何重现（必填）**
重现的步骤:
1.adb root
2.adb remount
3.adb shell setenforce 0
4 安装某apk

**期望的效果**
应该是高版本的手机不支持su指令，即使手机已经root aok有系统权限

**截图**
通过测试，如果不用su指令，便可以安装。

**Comment by zhubinsheng** [comment]
![Screenshot from 2022-01-26 11-42-31](https://user-images.githubusercontent.com/44765143/151100813-283cc244-ff43-44f0-8896-67dbafbfca3c.png)
请看stack info

**Comment by zhubinsheng** [comment]
![Screenshot from 2022-01-26 11-45-35](https://user-images.githubusercontent.com/44765143/151100860-781f3309-a8b7-451c-a0cd-2dd17ede4e1d.png)
![Screenshot from 2022-01-26 11-46-26](https://user-images.githubusercontent.com/44765143/151100872-855201eb-f547-48c1-83d1-79cef6e14739.png)

**Comment by xuexiangjys** [comment]
不同版本,不同平台都不太一样,框架无法做到全兼容适配. 
https://github.com/xuexiangjys/XUpdate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#9%E9%97%AE%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E8%AE%BE%E7%BD%AE%E4%BA%86isautomodetrue%E8%87%AA%E5%8A%A8%E7%89%88%E6%9C%AC%E6%9B%B4%E6%96%B0%E6%A8%A1%E5%BC%8F%E4%BD%86%E6%98%AF%E5%8D%B4%E6%97%A0%E6%B3%95%E5%81%9A%E5%88%B0%E8%87%AA%E5%8A%A8%E9%9D%99%E9%BB%98%E5%AE%89%E8%A3%85
