### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by cc365774016** [xuexiangjys/XUpdate#147]
**问题描述（必填）**
使用demo的时候根据leak的日志应该是toast的context内存泄露了

**使用的XUpdate版本（必填）**
  2.1.1

**如何重现（必填）**
重现的步骤:
1、DEMO 进入基础使用，傻瓜一键更新
2.点击默认更新
3.在弹出升级弹窗后再关闭网络，然后点击升级，由于无网会弹出toast提示失败，反复几次leak就出现了泄露提醒，

**截图**
![7df50338aa2976f247f2313bd7539fa](https://user-images.githubusercontent.com/21018428/163785377-c86af95f-9013-4686-9198-1ef5ab837841.jpg)

**Comment by xuexiangjys** [comment]
同这个问题
https://github.com/xuexiangjys/XUI/issues/134
