### ISSUE TITLE
空壳模板TemplateAppProject运行时在版本检测解析流程中-抛异常

### ISSUE THREAD

**Issue by shidawei8888** [xuexiangjys/XUpdate#150]
步骤：1.配置好了XUpdateService并部署到自己的测试服务器，各项测试都ok；
           2.配置部署好了xupdate-management并整合到xupdateservice的springboot中（作为静态资源），并测试ok;
           3.在版本更新管理后台添加了新版本成功（数据库检查到添加成功了）；
           4.对TemplateAppProject空壳模板进行配置（KEY_UPDATE_URL=服务端checkVersion接口地址），并将项目在真机运行；
           5.AS上logcat发现有异常抛出，导致版本检测流程没有正常执行完成；具体报错见截图。
![报错截图](https://user-images.githubusercontent.com/32774533/167454297-50b73c4d-b7db-4c64-9b2d-a8f07b056b45.png)

**Comment by xuexiangjys** [comment]
就很无语,麻烦使用之前多看看文档或者演示demo
https://github.com/xuexiangjys/XUpdate/wiki/%E6%9B%B4%E6%96%B0%E5%AE%9E%E4%BD%93%E5%AD%97%E6%AE%B5%E4%BB%8B%E7%BB%8D#%E9%BB%98%E8%AE%A4%E7%89%88%E6%9C%AC%E6%9B%B4%E6%96%B0%E8%BF%94%E5%9B%9E%E6%95%B0%E6%8D%AE%E7%9A%84%E6%A0%BC%E5%BC%8F

你要用的是下面这个
https://github.com/xuexiangjys/XUpdate/blob/master/app/src/main/java/com/xuexiang/xupdatedemo/custom/XUpdateServiceParser.java

**Comment by shidawei8888** [comment]
好的，谢谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月10日(周二) 凌晨0:35
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xuexiangjys/XUpdate] 空壳模板TemplateAppProject运行时在版本检测解析流程中-抛异常 (Issue #150)




 
就很无语,麻烦使用之前多看看文档或者演示demo
 https://github.com/xuexiangjys/XUpdate/wiki/%E6%9B%B4%E6%96%B0%E5%AE%9E%E4%BD%93%E5%AD%97%E6%AE%B5%E4%BB%8B%E7%BB%8D#%E9%BB%98%E8%AE%A4%E7%89%88%E6%9C%AC%E6%9B%B4%E6%96%B0%E8%BF%94%E5%9B%9E%E6%95%B0%E6%8D%AE%E7%9A%84%E6%A0%BC%E5%BC%8F
 
你要用的是下面这个
 https://github.com/xuexiangjys/XUpdate/blob/master/app/src/main/java/com/xuexiang/xupdatedemo/custom/XUpdateServiceParser.java
