### ISSUE TITLE
鸿蒙系统更新问题，提示不能安装

### ISSUE THREAD

**Issue by csh159** [xuexiangjys/XUpdate#159]
![1662083228503](https://user-images.githubusercontent.com/4157414/188041618-6cd1935d-154f-4a1b-8fd4-21a8b74749e3.png)

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
 - 设备名: [e.g. 华为P40+]
 - Android版本: [e.g. 鸿蒙2.0]
 - 设备型号 [e.g. ]
 - 系统版本（手机厂商定制rom）

**Comment by xuexiangjys** [comment]
我试了, 我在鸿蒙3.0上都是可以正常更新,没有问题的.
你这是用户权限的问题, 非程序的问题
