### ISSUE TITLE
2.1.3版本被google play拒了

### ISSUE THREAD

**Issue by miller8** [xuexiangjys/XUpdate#164]
![1679312854165](https://user-images.githubusercontent.com/9738748/226330942-cce41f3b-6fdf-4164-befe-aa66fa440bfa.jpg)

**Comment by miller8** [comment]
我们在下载地方已经做了兼容，但还是被google拒了，可能是被google扫描到相关代码

**Comment by xuexiangjys** [comment]
如果是发布在google play上的应用, 建议在google渠道包下不要打入XUpdate相关代码

**Comment by dupengyun** [comment]
你只要有下载apk和安装apk的代码逻辑，Google肯定不会让你过。Google只有play一个更新渠道，另外静默更新这种骚操作，现在基本国内都行不通，更何况Google play。

**Comment by miller8** [comment]
> 你只要有下载apk和安装apk的代号通讯，Google肯定不会让你过。Google只有玩一个更新的渠道，另外静默更新这种恶作剧，现在在国内都懒，Google更行不玩。

是的，会被机审扫描到

**Comment by miller8** [comment]
只能将Xupdate移除，应用已经上架google成功了
