### ISSUE TITLE
可以直接从构建UpdateEntity版本更新实体开始使用框架吗?

### ISSUE THREAD

**Issue by lishiyu1810** [xuexiangjys/XUpdate#166]
因为更新请求服务器，获取最新版本信息   已经自己实现

**Comment by xuexiangjys** [comment]
可以，具体参考：
https://github.com/xuexiangjys/XUpdate/blob/2519820bffc2820ed6ae9fe599a094ff6ada5ccf/app/src/main/java/com/xuexiang/xupdatedemo/fragment/AdvancedUseFragment.java#L67
