### ISSUE TITLE
安卓4.4.2无法使用,报错：java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

### ISSUE THREAD

**Issue by xisohi** [xuexiangjys/XUpdate#167]
**问题描述（必填）**
Android4.4.2系统，使用升级 出现报错：java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.。

**使用的XUpdate版本（必填）**
官方最新demo

**如何重现（必填）**
重现的步骤:
1、点击默认app更新
2、出现报错：java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

**期望的效果**
对你期望的效果进行清晰而简明的描述。

**截图**
![image](https://github.com/xuexiangjys/XUpdateAPI/assets/29686769/79b9daa7-a85c-446b-9e1b-6d402e4827bd)
![image](https://github.com/xuexiangjys/XUpdateAPI/assets/29686769/d8aae741-bc01-42fb-b8f3-e01b6d2acdb8)
![image](https://github.com/xuexiangjys/XUpdateAPI/assets/29686769/d9e62a4b-9f39-4a4c-85ce-281489def82b)
![image](https://github.com/xuexiangjys/XUpdateAPI/assets/29686769/beda49e2-eabd-4ee3-9c5b-f66b97690025)

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
 - 设备名: [e.g. 数码视讯Q7]
 - Android版本: [e.g. Android 4.2.2]
 - 设备型号 [e.g. ]
 - 系统版本（手机厂商定制rom）

**附加信息**
在此处添加任何有关该问题的任何其他说明。

**Comment by xuexiangjys** [comment]
网络请求失败,这是你的网络请求服务问题, 和本框架无关.
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found
这个很明显是你的证书有问题,建议你自己去查一下为什么证书验证不通过.
