### ISSUE TITLE
安装后自动删除apk包

### ISSUE THREAD

**Issue by evansherry** [xuexiangjys/XUpdate#169]
有办法实现安装后自动删除安装包吗？

**Comment by xuexiangjys** [comment]
这个不是框架所涉及的内容, 建议你还是按需自己进行处理吧.
获取框架默认存放安装包的路径:
https://github.com/xuexiangjys/XUpdate/blob/2519820bffc2820ed6ae9fe599a094ff6ada5ccf/xupdate-lib/src/main/java/com/xuexiang/xupdate/utils/UpdateUtils.java#L388
