### ISSUE TITLE
实现app更新的api是需要自己写么

### ISSUE THREAD

**Issue by zhouzelun** [xuexiangjys/XUpdate#173]
https://github.com/xuexiangjys/XUpdateService 请问一下，这里提供的后台接口是不是只能为前台维护界面负责，实现app的接口需要自己写。

**Comment by xuexiangjys** [comment]
不是的,基础的接口都是实现好了的.下面的两个接口就是为app提供的接口:
https://github.com/xuexiangjys/XUpdateService?tab=readme-ov-file#%E7%89%88%E6%9C%AC%E6%9B%B4%E6%96%B0%E6%8E%A5%E5%8F%A3
