### ISSUE TITLE
sdk8.0以上的权限问题

### ISSUE THREAD

**Issue by FyuSoft** [xuexiangjys/XUpdate#19]
首先谢谢你的作品，在实际使用中有以下问题反馈：
一、静默安装：在华为手机中直接服务被杀了，建议不开启静默安装的时候不要做root权限的检查
二、8.0以上没有申请REQUEST_INSTALL_PACKAGES权限的检查
三、建议下载地址不要二次解析，很多时候为了减轻服务器的压力，下载源都是放到oss上面去的

**Comment by xuexiangjys** [comment]
感谢你的反馈，我会找个时间修复一下的

**Comment by xuexiangjys** [comment]
今天试了一下，在8.0以上REQUEST_INSTALL_PACKAGES权限是无需动态申请的，暂不解决

**Comment by xuexiangjys** [comment]
在9.0的机器上也试了一遍，是可以正常进行版本更新的
