### ISSUE TITLE
这框架压根不能用

### ISSUE THREAD

**Issue by LiuSolomon** [xuexiangjys/XUpdate#2]
1：后台接口给的json串，按照你的方式一点都不行。
2：文档问题，后台数据跟接口完全对不上。

**Comment by xuexiangjys** [comment]
首先，文档写得那么仔细你不看我不能强求。
其次，后台接口你不按照规范接口来，又不会自己去自定义解析器，说文档有问题，你只给我看呢。
最后，你如果觉得不行可以不用，没人强制你用。
