### ISSUE TITLE
不太容易配置和成功

### ISSUE THREAD

**Issue by xxzztt** [xuexiangjys/XUpdate#26]
依赖太多了，想试验一下都没有成功。
先是：More than one file was found with OS independent path 'META-INF/rxjava.properties
后来：Couldn't load memtrack module //这个可能是那个依赖库没有加引起的。
不过最终配成功了。
XHttp2
这个依赖较多。开始没有加上 rxjava，rxandroid，总是闪退。
okhttp
这个依赖少一点。

总算成功了，谢谢。

**Comment by xuexiangjys** [comment]
XHttp2相对来说是比较重的网络请求框架了，如果你本身项目中就引用了还好，如果没引用的话就没必要引入了
