### ISSUE TITLE
代码里没有判断版本大小的功能吗？

### ISSUE THREAD

**Issue by tmxd09887** [xuexiangjys/XUpdate#3]
如果服务器端判断是否更新，那也要先从客户端发本地版本号过去吧？

这部分说明不太清楚，影响使用啊。

谢谢

**Comment by xuexiangjys** [comment]
对于此类问题我不过多说，麻烦请你把Android基础打打牢再来看，该项目只适合有一定Android基础的人。

**Comment by tmxd09887** [comment]
你的语文有问题吧？

你的文档里，没有版本判断的说明。VersionCode这个参数，怎么进行版本判断的也没说。

因为你借鉴的https://github.com/WVector/AppUpdate
我查了文档在
https://github.com/WVector/AppUpdate/blob/master/java.md
他判断是在后台

你的框架因为没有说明，全靠猜
.param("VersionCode", UpdateUtils.getVersionCode(this)) 
在这里设置本地版本，代码里有判断的逻辑，但是json文件里必须UpdateStatus清空，否则判断冲突

请问这跟android基础有什么关系？
