### ISSUE TITLE
弹出更新提示框后，摁Home

### ISSUE THREAD

**Issue by BantonSong** [xuexiangjys/XUpdate#31]
弹出更新提示框后，摁Home键回到手机主页面，报如下错误：
和是否开始下载无关，和是否强制更新无关。在华为meta20（9.0）和坚果Pro2s（8.1）上都报这个错。

    java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = **com.xuexiang.xupdate.entity.UpdateEntity**)
        at android.os.Parcel.writeSerializable(Parcel.java:1714)
        at android.os.Parcel.writeValue(Parcel.java:1662)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:875)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1583)

**Comment by xuexiangjys** [comment]
把你实现的IUpdateHttpService给我看一下

**Comment by BantonSong** [comment]
public class UpdateHttpService implements IUpdateHttpService {
    private BaseView baseView;
    private Context context;
    private boolean isShowLoadingIndicator;
    private RespObserver<AppVersionRespModel> respObserver;

    public UpdateHttpService(BaseView baseView, Context context, boolean isShowLoadingIndicator) {
        this.baseView = baseView;
        this.context = context;
        this.isShowLoadingIndicator = isShowLoadingIndicator;
    }

    @Override
    public void asyncGet(@NonNull String url, @NonNull Map<String, Object> params, @NonNull Callback callBack) {
    }

    @Override
    public void asyncPost(@NonNull String url, @NonNull Map<String, Object> params, @NonNull Callback callBack) {
        respObserver = new RespObserver<AppVersionRespModel>(baseView) {
            @Override
            public void onResponse(AppVersionRespModel respModel) {
                callBack.onSuccess(respModel.jsonStr);
            }

            @Override
            public void onError(Throwable t) {
                super.onError(t);
                callBack.onError(t);
            }
        }.useDefaultErrorHandler(false).showLoadingIndicator(isShowLoadingIndicator);

        AppVersionReqModel reqModel = new AppVersionReqModel();


        Network.getService().queryAppVersion(reqModel)
                .compose(new ApiTransformer<>(baseView))
                .subscribe(respObserver);
    }

    @Override
    public void download(@NonNull String url, @NonNull String path, @NonNull String fileName, @NonNull DownloadCallback callback) {
        File file = new File(path + fileName);

        Observable.create(new ObservableOnSubscribe<Progress>() {
            @SuppressLint("CheckResult")
            @Override
            public void subscribe(ObservableEmitter<Progress> emitter) {
                Progress progress = new Progress();
                Network.getInstance()
                        .createFileService(context)
                        .downloadFile(url).subscribe(new Consumer<ResponseBody>() {

                    @Override
                    public void accept(ResponseBody responseBody) throws Exception {
                        //创建文件
                        if (!file.exists()) {
                            if (!file.getParentFile().exists()) {
                                file.getParentFile().mkdir();
                            }
                            file.createNewFile();
                        }

                        InputStream is = responseBody.byteStream();
                        long totalLength = responseBody.contentLength();

                        int sBufferSize = 1024;
                        OutputStream os = null;
                        float currentLength = 0;
                        try {
                            os = new BufferedOutputStream(new FileOutputStream(file));
                            byte data[] = new byte[sBufferSize];
                            int len;
                            while ((len = is.read(data, 0, sBufferSize)) != -1) {
                                os.write(data, 0, len);
                                currentLength += len;
                                //计算当前下载进度
                                progress.progress = currentLength / totalLength;
                                progress.total = totalLength;
                                emitter.onNext(progress);
                            }
                            //下载完成，并返回保存的文件路径
                            emitter.onComplete();
                        } finally {
                            try {
                                is.close();
                            } catch (IOException e) {
                                e.printStackTrace();
                            }
                            try {
                                if (os != null) {
                                    os.close();
                                }
                            } catch (IOException e) {
                                e.printStackTrace();
                            }
                        }
                    }
                });
            }
        }).subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Observer<Progress>() {
                    @Override
                    public void onSubscribe(Disposable d) {
                        callback.onStart();
                    }

                    @Override
                    public void onNext(Progress progress) {
                        callback.onProgress(progress.progress, progress.total);
                    }

                    @Override
                    public void onError(Throwable e) {
                        e.printStackTrace();
                        callback.onError(e);
                    }

                    @Override
                    public void onComplete() {
                        callback.onSuccess(file);
                    }
                });
    }

    @Override
    public void cancelDownload(@NonNull String url) {
        if (respObserver != null) {
            Disposable disposable = respObserver.getDisposable();
            if (disposable != null && !disposable.isDisposed()) {
                disposable.dispose();
            }
        }
    }

    class Progress {
        float progress;
        long total;
    }
}

**Comment by xuexiangjys** [comment]
就知道你这么写，IUpdateHttpService中不可以持有非基础性数据

**Comment by xuexiangjys** [comment]
IUpdateHttpService的实现还是参考demo中的写法，否则序列化会出问题
