### ISSUE TITLE
我的手机Root了，但设置了全局auto为false，下载完一直在申请root权限

### ISSUE THREAD

**Issue by zhouhuping** [xuexiangjys/XUpdate#34]
为何会这样啊？   下载完一直在申请root 权限， 我希望的是 调用系统的安装程序

**Comment by zhouhuping** [comment]
没有root的手机 倒是 调用系统的安装程序

**Comment by xuexiangjys** [comment]
默认的安装是检测到有root的话就申请root权限静默安装，不希望这种效果的话可以自定义安装器进行替代

**Comment by xuexiangjys** [comment]
自定义的话，可参考：https://github.com/xuexiangjys/XUpdate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%9A%84%E9%97%AE%E9%A2%98

**Comment by zhouhuping** [comment]
好的。请你加个控制吧。
