### ISSUE TITLE
下载完成后会有警告

### ISSUE THREAD

**Issue by SunTaolin** [xuexiangjys/XUpdate#35]
查看log信息会发现有如下警告
java.io.IOException: Cannot run program "su": error=13, Permission denied
但是应用安装界面能够正常弹出

**Comment by yanjingtp** [comment]
这是因为你没有root权限，或者app没有获取root权限吧

**Comment by zhubinsheng** [comment]
> 这是因为你没有root权限，或者app没有获取root权限吧，自动安装是需要root权限的

不 root了的手机系统app也没发安装 我认为su这个指令在高版本不支持
