### ISSUE TITLE
获取的下载文件名称有特殊字符的话无法安装，建议过滤下特殊字符

### ISSUE THREAD

**Issue by gxp3635** [xuexiangjys/XUpdate#36]
/**
     * 根据下载地址获取文件名
     *
     * @param downloadUrl
     * @return
     */
    @NonNull
    public static String getApkNameByDownloadUrl(String downloadUrl) {
        if (TextUtils.isEmpty(downloadUrl)) {
            return "temp.apk";
        } else {
            String appName = downloadUrl.substring(downloadUrl.lastIndexOf("/") + 1, downloadUrl.length());
            if (!appName.endsWith(".apk")) {
                appName = "temp.apk";
            }
            return appName;
        }
    }
    /**
     * 过滤文件名非法字符
     */
    private static Pattern FilePattern = Pattern.compile("[\\\\/:*?\"<>|]");

    public static String filenameFilter(String str) {
        return str == null ? null : FilePattern.matcher(str).replaceAll("");
    }

**Comment by xuexiangjys** [comment]
框架不会去做这些多余的操作，如果需要过滤的话，可以在IUpdateHttpService 中由使用者自行进行处理
