### ISSUE TITLE
根据Demo配置的XUpdateServiceFragment强制更新，还是有x号

### ISSUE THREAD

**Issue by hufu4635** [xuexiangjys/XUpdate#4]
这个x号怎么取消掉，我用Demo配置了下自己的数据URIL环境   Demo的就没有x号，这是为什么

**Comment by xuexiangjys** [comment]
那是你的数据解析不对，没有识别成强制更新。如需强制更新，请严格按照接口规范来，否则请自定义解析器。

**Comment by hufu4635** [comment]
是对的啊，我把接口移动到DemoAPP中就没有了x号 其他的都是参考的Demoapp配置的
` XUpdate.get()
                .isWifiOnly(true)     //默认设置只在wifi下检查版本更新
                .isGet(false)          //默认设置使用get请求检查版本
                .isAutoMode(false)    //默认设置非自动模式，可根据具体使用配置
                .param("versionCode", versionCode) //设置默认公共请求参数
                .param("appKey", appKey)
//                .debug(true)
                .setOnUpdateFailureListener(new OnUpdateFailureListener() { //设置版本更新出错的监听
                    @Override
                    public void onFailure(UpdateError error) {
                        ToastUtils.showToast(error.toString());
                    }
                })
                .setIUpdateHttpService(new XHttpUpdateHttpService(MyUrl.version)) //这个必须设置！实现网络请求功能。
                .init(this);   //这个必须初始化`
` //app强制版本升级代码
        XUpdate.newBuild(this)
                .isGet(false)
                .param("appKey", "包名")
                .updateUrl(XUpdateServiceParser.getVersionCheckUrl())
                .updateParser(new XUpdateServiceParser())
                .update();`

**Comment by xuexiangjys** [comment]
你把你版本检查请求的返回数据贴一下
