### ISSUE TITLE
更新错误的提示国际化了吗

### ISSUE THREAD

**Issue by moujunqiang** [xuexiangjys/XUpdate#40]
比如当前版本已忽略 下载错误这些提示有英文版的嘛

**Comment by xuexiangjys** [comment]
国际化目前只做了UI展示相关的，错误目前并没有做

**Comment by xuexiangjys** [comment]
目前已完成错误信息的国际化：
15f2d0d1e8fd572b0e2a6567f72ea2c91cdd7f01

**Comment by moujunqiang** [comment]
谢谢你的及时回复，通过gradle依赖的方式使用好像没有英文版的。下载代码是有的

**Comment by xuexiangjys** [comment]
@moujunqiang 暂时还没发布
