### ISSUE TITLE
自定义解析器下载更新

### ISSUE THREAD

**Issue by guoerming** [xuexiangjys/XUpdate#45]
自定义解析器强更下载安装后，后台再次上传一个强更新版本点击检测更新一直弹的是选更的弹框，自定义实体解析 if (result != null) {
            return new UpdateEntity()
                    .setHasUpdate(isupdate)
                    .setIsIgnorable(false)
                    .setForce(isForce)
                    .setVersionCode(result.getVersionCode())
                    .setVersionName(result.getVersionName())
                    .setUpdateContent(result.getUpdateIntro())
                    .setDownloadUrl(result.getFileName())
                    .setSize(1000);
        }这个一直没走，安装新版本之前会走到这里，安装后有新版本就没走了

**Comment by xuexiangjys** [comment]
这种问题你应该打断点调试，结合日志来排查问题。你问题都没搞清楚，我怎么帮你解决？
