### ISSUE TITLE
why i can't set post json format to server ?

### ISSUE THREAD

**Issue by lianchengtong** [xuexiangjys/XUpdate#46]
private static final MediaType JSON = MediaType.parse("application/json; charset=utf-8");
RequestBody body = RequestBody.create(JSON, gson.toJson(param));
i often use okhttp3 like above setting format for transfer ,how about xupdate do it ?

**Comment by xuexiangjys** [comment]
demo中默认使用的是okhttputils实现的IUpdateHttpService,且默认使用的post方式是form表单格式,这里你可以修改使用postString或者自己实现一个IUpdateHttpService,不是很难.

**Comment by xuexiangjys** [comment]
详细参见新添加的注释:
f1a76e76dbf6be235c6fc92640ca299d29e18675
