### ISSUE TITLE
设置supportBackgroundUpdate(true)，Force强制更新时，还可以进入后台更新

### ISSUE THREAD

**Issue by Neils320** [xuexiangjys/XUpdate#48]

**Comment by xuexiangjys** [comment]
业务的问题请不要在这里提！！！
框架不可能考虑到所有人的情况（何况很多时候需求都是矛盾的）。
你可以在强制更新时，设置supportBackgroundUpdate(false)就行了。

**Comment by Neils320** [comment]
可是你的代码逻辑并不能这样实现

**Comment by xuexiangjys** [comment]
框架不会被业务绑架，这违反依赖倒置原则，所以你还是自己做处理吧
