### ISSUE TITLE
XUpdate.get().init() 必须传入Application

### ISSUE THREAD

**Issue by superchenwb** [xuexiangjys/XUpdate#49]
感谢作者，我并不是原生的Android开发者，我使用的是react-native来创建我的项目，我写了一个react-native插件来封装你的update功能，但是init方法需要接受application，导致我的封装产生了一些问题。我看过你的源代码，其实传入context对象也是一样的，我不得不fork一份你的代码，以便于在我的项目中使用。可否将这个修改一下。感谢

**Comment by xuexiangjys** [comment]
设计就是这么设计的，强制在Application里初始化。不过context.getApplicationContext()可以直接强转成application,也是一样的
```
((Application)context.getApplicationContext())
```
