### ISSUE TITLE
老哥，能暴露一个改按钮颜色的属性吗

### ISSUE THREAD

**Issue by xiaoduv587** [xuexiangjys/XUpdate#5]
private void setDialogTheme(int color, int topResId) {
        mIvTop.setImageResource(topResId);
        mBtnUpdate.setBackgroundDrawable(DrawableUtils.getDrawable(UpdateUtils.dip2px(4, getContext()), color));
        mNumberProgressBar.setProgressTextColor(color);
        mNumberProgressBar.setReachedBarColor(color);
        //随背景颜色变化
        mBtnUpdate.setTextColor(ColorUtils.isColorDark(color) ? Color.WHITE : Color.BLACK);
    }

这一段，，我的项目是只用白色的。。

**Comment by xuexiangjys** [comment]
你要么就把升级的主题颜色改成深色，要么你就重写Ui,然后自己设置进去，要么你就fork一下项目，自己改一下。
