### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by lengye2014** [xuexiangjys/XUpdate#50]
建议添加一种模式为，自动点击更新按钮。比静默模式更为友好
用户无需点击更新按钮，且可以直观看到更新进度

**Comment by fdtl01** [comment]
你们跑通了吗，我这边不清楚为啥一直打印It's the latest version!，代码我跟踪到这里，感觉过不去，你们环境有这个问题吗？
![image](https://user-images.githubusercontent.com/36351484/60231510-053aca00-98cc-11e9-90dc-3928c6bf8b36.png)

**Comment by lengye2014** [comment]
没有问题，多检查检查代码

**Comment by xuexiangjys** [comment]
框架只负责流程的控制和提供一套默认的实现业务,你说的这些都可以定制完成,框架不管这些
