### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by hustliubo** [xuexiangjys/XUpdate#51]
麻烦问下，如何查看安装失败具体错误码，现在只能看到自定义的5000

**Comment by xuexiangjys** [comment]
安装失败看文档说明:
https://github.com/xuexiangjys/XUpdate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E6%8E%A5%E5%85%A5%E7%9A%84%E9%97%AE%E9%A2%98
