### ISSUE TITLE
解析软件包时出现问题

### ISSUE THREAD

**Issue by sugela** [xuexiangjys/XUpdate#52]
1.设备信息 小米mix2  miui10 9.6.27 安卓9
2.代码信息
application
![image](https://user-images.githubusercontent.com/17471079/60430547-297e0a00-9c30-11e9-998c-acc430752c03.png)
activity
![image](https://user-images.githubusercontent.com/17471079/60430571-34389f00-9c30-11e9-826c-55d6cfcec1e4.png)
3.后台返回信息
![image](https://user-images.githubusercontent.com/17471079/60430500-09e6e180-9c30-11e9-9d47-88a97533409f.png)
4.报错
![image](https://user-images.githubusercontent.com/17471079/60430669-719d2c80-9c30-11e9-8f07-aa78b7ab3b5f.png)

**Comment by xuexiangjys** [comment]
请按照[常见问题](https://github.com/xuexiangjys/XUpdate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E6%8E%A5%E5%85%A5%E7%9A%84%E9%97%AE%E9%A2%98)中的第4点逐步排查问题.
另外,你下载的这个貌似不是.apk文件,可能需要自定义安装监听
