### ISSUE TITLE
如果下载途中，突然断网了，弹窗就这样消失了，强制升级还有什么用？

### ISSUE THREAD

**Issue by Alexxiaopang** [xuexiangjys/XUpdate#56]
下载途中，突然断网了，弹窗就消失了，不应该弹窗还在的么，如果不在，强制升级的意义在哪里？强制升级就算出现异常了，弹窗也不应消失，弹出对应的异常信息就好

**Comment by xuexiangjys** [comment]
这里的强制更新只是隐藏了忽略和关闭按钮，强制用户点更新按钮而已，再说能不能更新成功不是我框架负责的东西，这些都是你自己想要的业务需求，不要绑架框架，这样违反依赖倒置原则.

**Comment by Alexxiaopang** [comment]
你应该理解错了，强制升级的弹窗都是最顶层的，你可以看一下其他的升级框架，强制升级不仅仅是隐藏关闭按钮，强制升级永远在顶层，用户操作不了app的内容，必须升级

**Comment by xuexiangjys** [comment]
小兄弟，不要和我谈业务需求，框架不可能什么都帮你做好，这些东西需要你自己写，框架只负责流程性的东西。你如果觉得我的框架帮不了你，你可以选择其他可以拿来就用的，选择适合自己的就行了。
