### ISSUE TITLE
功能建议和咨询

### ISSUE THREAD

**Issue by shijunti19** [xuexiangjys/XUpdate#57]
**提Bug前需要做的事情**
**问题描述**
![image](https://user-images.githubusercontent.com/5392211/61258184-f054a680-a7a6-11e9-8ace-6a99135e9929.png)
1.希望增加可以在json里远程定义图片和颜色，我把你这个做成了插件，所以无法传入资源id
2.怎么传入head，我把升级json弄在jwt里，需要传授权，就是不知道怎么传head，因为jwt的版本号v1必须在head传
**如何重现**

**期望的效果**

**截图**

**设备信息**

**Comment by xuexiangjys** [comment]
1.对于第一个问题,可以自定义版本更新提示器`IUpdatePrompter`来实现
2.对于第一个问题,可以通过在实现`IUpdateHttpService `的时候,自己传入head即可

**Comment by shijunti19** [comment]
@xuexiangjys  不熟悉怎么传入在线图片，java不熟悉https://ubmcmm.baidustatic.com/media/v1/0f000AjvfvBF4fQUL5fNZs.jpg例如这种图片地址，怎么加载

**Comment by xuexiangjys** [comment]
直接使用Glide就行了
