### ISSUE TITLE
为什么我在android studio直接run调试运行的时候可以提示升级，打包成apk安装后，就不会提示升级了

### ISSUE THREAD

**Issue by super-qc** [xuexiangjys/XUpdate#59]
为什么我在android studio直接run调试运行的时候可以提示升级，打包成apk安装后，就不会提示升级了
直接用android studio run调试，日志中显示“发现新版本...”，弹出了提示窗
打包成apk后，日志中也没有显示“发现新版本”

**Comment by xuexiangjys** [comment]
不符合要求的issue, 建议出现问题多看看文档:[常见问题](https://github.com/xuexiangjys/XUpdate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

**Comment by super-qc** [comment]
解决了，因为少了混淆的配置
