### ISSUE TITLE
进度条不动

### ISSUE THREAD

**Issue by feifei8688** [xuexiangjys/XUpdate#6]
进度条一直显示不动，点升级，但文件在下载

**Comment by xuexiangjys** [comment]
进度条不加载那是你的下载地址有问题

**Comment by xuexiangjys** [comment]
哦，好的好的

**Comment by feifei8688** [comment]
非常感谢

**Comment by hellomrfool** [comment]
> 非常感谢

请问怎么改，我也遇到问题，没看懂你解决的方式。能详细跟我说下吗？
我的Progress打印出来时负数 晕了。

**Comment by lzjin** [comment]
同样遇到这个问题，自定义的json格式。一定要用提供的格式？

**Comment by xuexiangjys** [comment]
还有不明白的,请自行去wiki中查看[常见问题](https://github.com/xuexiangjys/XUpdate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#3%E9%97%AE%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E7%82%B9%E5%87%BB%E4%B8%8B%E8%BD%BD%E5%90%8E%E6%96%87%E4%BB%B6%E6%98%AF%E8%83%BD%E4%B8%8B%E8%BD%BD%E4%B8%8B%E6%9D%A5%E7%9A%84%E4%BD%86%E6%98%AF%E8%BF%9B%E5%BA%A6%E6%9D%A1%E4%B8%8D%E6%9B%B4%E6%96%B0%E6%88%96%E8%80%85%E6%89%93%E5%8D%B0%E5%87%BA%E8%BF%9B%E5%BA%A6%E6%9D%A1%E7%9A%84%E5%80%BC%E6%98%AF-1)
