### ISSUE TITLE
md5计算存在问题

### ISSUE THREAD

**Issue by kangsafe** [xuexiangjys/XUpdate#63]
apk文件大小46M，出现奔溃，追踪的问题根源在Md5Utils.getFileMD5方法抛出异常，进行如下修改：
MessageDigest digest = MessageDigest.getInstance("MD5");
            in = new FileInputStream(file);
            byte[] buffer = new byte[1024];//10k
            int readLen;
            while ((readLen = in.read(buffer)) != -1) {
                digest.update(buffer, 0, readLen);
            }

**Comment by xuexiangjys** [comment]
问题已经改了：
dfb82c6dae3fb4f27c3dfd82636a3f44e2282165
暂时不发新版本，你可以重写一下[DefaultInstallListener](https://github.com/xuexiangjys/XUpdate/blob/master/xupdate-lib/src/main/java/com/xuexiang/xupdate/listener/impl/DefaultInstallListener.java)的`checkApkFile`方法暂时先用着
