### ISSUE TITLE
下载失败，在此下载无效，如何再次下载？

### ISSUE THREAD

**Issue by unweixiaoyy** [xuexiangjys/XUpdate#64]
RT

**Comment by xuexiangjys** [comment]
麻烦把问题说详细一点：[模板](https://github.com/xuexiangjys/XUpdate/issues/new?assignees=&labels=&template=--bug--.md&title=)

**Comment by xuexiangjys** [comment]
想要下载失败的适合,弹窗不消失需要自定义版本更新提示器IUpdatePrompter
