### ISSUE TITLE
如何获取用户点击取消升级的事件？

### ISSUE THREAD

**Issue by folousiot** [xuexiangjys/XUpdate#69]
服务器端设置的APK不是强制更新模式。业务上需要在用户点击更新弹窗下面的叉时，执行另外一些操作。有没有办法获取到此事件？

**Comment by xuexiangjys** [comment]
自定义下载器，给你个例子：
https://github.com/xuexiangjys/XUI/blob/master/app/src/main/java/com/xuexiang/xuidemo/utils/update/CustomUpdateDownloader.java

**Comment by folousiot** [comment]
多谢。
另外再问一下，SDK是否有什么方法判断自动更新APK相关操作已经执行完成。因为我这操作是要等自动更新完成后，再执行的。
因为工具包是异步执行的，目前我是没有找到判断是否完成，所以才想在没有版本更新或者用户取消更新时调用这两个操作。若能判断相关操作已经执行完成就更好。

**Comment by xuexiangjys** [comment]
只能知道什么时候触发安装的事件，至于有没有安装成功不能保证，需要你自定义安装监听器来实现

**Comment by folousiot** [comment]
好的，多谢。
