### ISSUE TITLE
返回json格式可以改吗？ 

### ISSUE THREAD

**Issue by lzjin** [xuexiangjys/XUpdate#73]
返回json格式可以改吗？ 我们是全部接口类似这种
{
"code": "200",
"message": "获取成功",
"data":"xxx"
}

**Comment by xuexiangjys** [comment]
可以自定义版本更新解析器IUpdateParser：
https://github.com/xuexiangjys/XUpdate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%9A%84%E9%97%AE%E9%A2%98
