### ISSUE TITLE
强制更新，在没有授权的时候，弹窗直接关闭了

### ISSUE THREAD

**Issue by dev-cell** [xuexiangjys/XUpdate#75]
代码位置UpdateDialogFragment.onRequestPermissionsResult()

**Comment by xuexiangjys** [comment]
* 既然用户都已经拒绝授权了，就没必要继续做得那么流氓了。
* 这里每个人的需求都不一样，照顾了这边，那边又不能周全，框架提供的只是一个默认通用的解决方案。
* 这里我建议你根据自己的需求自己修改一下，然后自定义IUpdatePrompter显示
