### ISSUE TITLE
现在我使用更新解析器后更新后进入主页面报错：查询失败，解析json错误。我只是用下载功能，更新后进入界面还是给我提示：查询失败，解析json错误。

### ISSUE THREAD

**Issue by ygzm-lxh** [xuexiangjys/XUpdate#77]
**提Bug前需要做的事情**

1.如果是集成问题的话，请保证仔细按照[如何引用](https://github.com/xuexiangjys/XUpdate/wiki/%E5%A6%82%E4%BD%95%E5%BC%95%E7%94%A8)的步骤，一步一步来，不要跳步骤！
2.详细阅读过[使用手册](https://github.com/xuexiangjys/XUpdate/wiki)，并且确保是框架的问题。
3.参考[常见问题](https://github.com/xuexiangjys/XUpdate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98),可以解决你出现的绝大多数问题!

> 如果以上都不能解决你的问题,那么请按照以下说明仔细填写信息,这里需要说明的是:不符合填写要求的issue一律不予理会,希望这样能节约大家的时间!

----

**问题描述（必填）**
对问题进行清晰而简明的描述，把握问题的关键点。

**使用的XUpdate版本（必填）**

**如何重现（必填）**
重现的步骤:

**期望的效果**
对你期望的效果进行清晰而简明的描述。

**截图**
如果方便的话，贴一下程序截图和代码片段以帮助解释您的问题。

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
 - 设备名: [e.g. 华为P20]
 - Android版本: [e.g. Android 7.0]
 - 设备型号 [e.g. ]
 - 系统版本（手机厂商定制rom）

**附加信息**
在此处添加任何有关该问题的任何其他说明。

**Comment by ygzm-lxh** [comment]
你是不是有缓存没清理呀，以前报过这种错，然后就一直给我报错提示，无论我重新安装还是什么一直存在这个错误信息。

**Comment by xuexiangjys** [comment]
没有缓存!!
还有你到底是要用更新解析器还是下载功能???问题都说不明白.
没事多看看使用文档:https://github.com/xuexiangjys/XUpdate/wiki/%E9%AB%98%E9%98%B6%E4%BD%BF%E7%94%A8#%E5%8F%AA%E4%BD%BF%E7%94%A8xupdate%E7%9A%84%E4%B8%8B%E8%BD%BD%E5%99%A8%E5%8A%9F%E8%83%BD%E8%BF%9B%E8%A1%8Capk%E7%9A%84%E4%B8%8B%E8%BD%BD

**Comment by ygzm-lxh** [comment]
我一开始使用的更新解析器，后来改成只使用下载功能，他们都能更新，更新版本后在进入主页都是显示这个错误。







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "薛翔"<notifications@github.com&gt;; 
发送时间: 2020年1月18日(星期六) 晚上7:50
收件人: "xuexiangjys/XUpdate"<XUpdate@noreply.github.com&gt;; 
抄送: "李晓浩"<2510515705@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [xuexiangjys/XUpdate] 现在我使用更新解析器后更新后进入主页面报错：查询失败，解析json错误。我只是用下载功能，更新后进入界面还是给我提示：查询失败，解析json错误。 (#77)




没有缓存!!
 还有你到底是要用更新解析器还是下载功能???问题都说不明白.
 没事多看看使用文档:https://github.com/xuexiangjys/XUpdate/wiki/%E9%AB%98%E9%98%B6%E4%BD%BF%E7%94%A8#%E5%8F%AA%E4%BD%BF%E7%94%A8xupdate%E7%9A%84%E4%B8%8B%E8%BD%BD%E5%99%A8%E5%8A%9F%E8%83%BD%E8%BF%9B%E8%A1%8Capk%E7%9A%84%E4%B8%8B%E8%BD%BD

**Comment by xuexiangjys** [comment]
报错都那么明显了,你就不能打断点或者看日志自己解决?
很明显是你更新新版本后,后台返回的json内容解析不成功

**Comment by ygzm-lxh** [comment]
您说的对，我找到打印这个错误的地方了，我注释掉之后还是弹出这个错误，后来我把报错方法都给注释掉了还是弹出这个错误。
而且还有一个问题，我使用更新解析器的时候弹出这个错误还是情有可原，毕竟我传过去的是更新接口的地址，但是我只使用下载功能时传过去的是个下载地址，他还是弹出这个错误就有点不合理了，这才求助到您这。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"薛翔"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月19日(星期天) 凌晨0:20
收件人:&nbsp;"xuexiangjys/XUpdate"<XUpdate@noreply.github.com&gt;;
抄送:&nbsp;"李晓浩"<2510515705@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xuexiangjys/XUpdate] 现在我使用更新解析器后更新后进入主页面报错：查询失败，解析json错误。我只是用下载功能，更新后进入界面还是给我提示：查询失败，解析json错误。 (#77)




报错都那么明显了,你就不能打断点或者看日志自己解决?
 很明显是你更新新版本后,后台返回的json内容解析不成功

**Comment by xuexiangjys** [comment]
麻烦你看文档或者使用演示再问，ok？这个是你自己调用的，和框架无关！！！！！
