### ISSUE TITLE
引用问题

### ISSUE THREAD

**Issue by zhubinsheng** [xuexiangjys/XUpdate#80]
ERROR: Android dependency 'com.github.xuexiangjys:XUpdate:1.1.3' is set to compileOnly/provided which is not supported
 compileSdkVersion 29
    useLibrary 'org.apache.http.legacy'
    defaultConfig   {
        minSdkVersion 16
        targetSdkVersion 29
        versionCode 1
        versionName "1.00.00"
        multiDexEnabled true
        ndk {
            // 设置支持的SO库架构
            abiFilters 'armeabi', 'x86' //, 'x86', 'armeabi-v7a', 'x86_64', 'arm64-v8a'
        }
        renderscriptTargetApi 25
        renderscriptSupportModeEnabled true

是因为我不是安卓x吗

**Comment by zhubinsheng** [comment]
还要自己实现可能会之前代码冲突的OKHttpUpdateHttpService

**Comment by xuexiangjys** [comment]
What are you talking about???

**Comment by zhubinsheng** [comment]
为啥必须使用Gson框架啊

**Comment by xuexiangjys** [comment]
没说一定要使用gson 啊,如果不想使用gson你可以自己定义解析器`IUpdateParser`
