### ISSUE TITLE
使用流量更新的时候报错，已设置isWifiOnly(false)   

### ISSUE THREAD

**Issue by zbyJade** [xuexiangjys/XUpdate#82]
Application中设置了isWifiOnly(false)

**Comment by xuexiangjys** [comment]
请按模板填写详细错误信息，以便查找问题。否则3日之内自动删除

**Comment by zbyJade** [comment]
使用demo中的升级功能时，连接wifi时能下载更新成功，但是如果连接4g更新的话，会提示CHECK_NO_NEW_VERSION的错误

**Comment by xuexiangjys** [comment]
[模板链接](https://github.com/xuexiangjys/XUpdate/issues/new?assignees=&labels=&template=--bug--.md&title=)

**Comment by zbyJade** [comment]
个人操作问题
