### ISSUE TITLE
没有兼容Android10，无法正常下载

### ISSUE THREAD

**Issue by ttcluo** [xuexiangjys/XUpdate#83]
**问题描述（必填）**
Android10系统，使用升级 出现下载失败问题

**使用的XUpdate版本（必填）**
官方最新demo

**如何重现（必填）**
重现的步骤:
1. 点击默认app升级
2. 点击升级
3. 出现进度条但是无法下载
4. 提示下载失败

**期望的效果**
对你期望的效果进行清晰而简明的描述。

**截图**
如果方便的话，贴一下程序截图和代码片段以帮助解释您的问题。

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
 - 设备名: [华为mate 20X]
 - Android版本: [e.g. Android 10]
 - 设备型号 [EVR-AL00]
 - 系统版本（EMUI10）

**附加信息**
在此处添加任何有关该问题的任何其他说明。

**Comment by xuexiangjys** [comment]
麻烦看清楚报错，那是github资源被墙了，和Android10半毛钱关系都没有

**Comment by xuexiangjys** [comment]
我把资源链接修改为阿里云了，你重新下载安装演示app再试一下

**Comment by ttcluo** [comment]
> 我把资源链接修改为阿里云了，你重新下载安装演示app再试一下
正常了，谢谢🙏
