### ISSUE TITLE
依赖，然后编译报错，应该是与gradle版本方法和这个库之间的的api不匹配的问题

### ISSUE THREAD

**Issue by 17828127004** [xuexiangjys/XUpdate#91]
INFO: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.

具体报错地方
Android resource compilation failed C:\Users\yangchun\.gradle\caches\transforms-2\files-2.1\7a3b48fda69d1ce4599b3de78b9bd228\XUpdate-1.1.3\res\values\values.xml:65:5-84:25: AAPT: error: duplicate value for resource 'attr/progress_text_visibility' with config ''.      C:\Users\yangchun\.gradle\caches\transforms-2\files-2.1\7a3b48fda69d1ce4599b3de78b9bd228\XUpdate-1.1.3\res\values\values.xml:65:5-84:25: AAPT: error: resource previously defined here.      D:\work\imeng_kj\project_code\luwu_android\tianYueMobileOA\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml: AAPT: error: file failed to compile. |  
-- | --

**Comment by xuexiangjys** [comment]
和gradle版本没有半毛钱关系!是attr/progress_text_visibility资源名重复定义了,如果引用了https://github.com/daimajia/NumberProgressBar,可以考虑去除

**Comment by 17828127004** [comment]
确实是，thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"薛翔"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月23日(星期四) 凌晨1:26
收件人:&nbsp;"xuexiangjys/XUpdate"<XUpdate@noreply.github.com&gt;;
抄送:&nbsp;"守護甜心"<172828913@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xuexiangjys/XUpdate] 依赖，然后编译报错，应该是与gradle版本方法和这个库之间的的api不匹配的问题 (#91)





 
和gradle版本没有半毛钱关系!是attr/progress_text_visibility资源名重复定义了,如果引用了https://github.com/daimajia/NumberProgressBar,可以考虑去除
