### ISSUE TITLE
能不能加个弹窗弹出与关闭的回调

### ISSUE THREAD

**Issue by shaojiankui** [xuexiangjys/XUpdate#94]
我把检测更新放在了onResume中进行实时版本检测。首次启动onResume调用多次，或者频繁切后台前台。导致更新框弹出多次。
我看你的代码中有判断是否有更新弹窗显示但这个，对于我这个情况不适用啊。连续调用两次checkVersion，isShowUpdatePrompter仍为false呢。

` if (DownloadService.isRunning() || _XUpdate.isShowUpdatePrompter()) {
            updateProxy.onAfterCheck();
            _XUpdate.onUpdateError(CHECK_UPDATING);
            return;
        }`

所以能不能加个Listener，返回 isShowUpdatePrompter的改变。

**Comment by xuexiangjys** [comment]
这个你可以通过自定义`IUpdateChecker` 或者`IUpdatePrompter`来实现自己的个性需求

**Comment by shaojiankui** [comment]
加个两次弹出时间间隔校验就好啦。。。
