### ISSUE TITLE
Gradle DSL method not found: 'implementation()'

### ISSUE THREAD

**Issue by ftlh2005** [xuexiangjys/XUpdate#95]
Gradle DSL method not found: 'implementation()'
Possible causes:
The project 'My Application' may be using a version of the Android Gradle plug-in that does not contain the method (e.g. 'testCompile' was added in 1.1.0).
Upgrade plugin to version 4.0.0 and sync project

The project 'My Application' may be using a version of Gradle that does not contain the method.
Open Gradle wrapper file

The build file may be missing a Gradle plugin.
Apply Gradle plugin

**Comment by xuexiangjys** [comment]
可以百度的麻烦不要来浪费别人的时间,谢谢
