### ISSUE TITLE
调用_XUpdate.encryptFile(file);  没有返回md5

### ISSUE THREAD

**Issue by dancheng99** [xuexiangjys/XUpdate#97]
**问题描述（必填）**
调用_XUpdate.encryptFile(file);  没有返回md5

**使用的XUpdate版本（必填）**
// androidx版本
  implementation 'com.github.xuexiangjys:XUpdate:2.0.1'

**如何重现（必填）**
重现的步骤:
1. 
 button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                File file = new File("E:\\workspace\\xutiltest\\apk\\2.apk");
                System.out.println(file);
                String s = _XUpdate.encryptFile(file);
                Toast.makeText(getContext(), s.toString(), Toast.LENGTH_SHORT).show();
                System.out.println(s);

            }
        });

2.  s为空 file是存在的没问题

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
android studio 虚拟机

**Comment by xuexiangjys** [comment]
一个Android api你传个PC的路径？你在想什么呢？？？

**Comment by dancheng99** [comment]
> 一个Android api你传个PC的路径？你在想什么呢？？？
傻了哈哈

**Comment by zhangjingex** [comment]
笑死我了

**Comment by zhangjingex** [comment]
笑死我了，我就是来看看有哪些奇葩问题的
